// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

const encoding0_enum = {
  info: 1,
  error: 2,
  debug: 3
}

// @wdk-core/log-type-enum enum
const encoding0 = {
  preencode (state, m) {
    state.end++ // max enum is 3 so always one byte
  },
  encode (state, m) {
    if (m > 3) throw new Error('Unknown enum')
    c.uint.encode(state, m)
  },
  decode (state) {
    return c.uint.decode(state)
  }
}

// @wdk-core/log-request
const encoding1 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.type) encoding0.preencode(state, m.type)
    if (m.data) c.string.preencode(state, m.data)
  },
  encode (state, m) {
    const flags =
      (m.type ? 1 : 0) |
      (m.data ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.type) encoding0.encode(state, m.type)
    if (m.data) c.string.encode(state, m.data)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      type: (flags & 1) !== 0 ? encoding0.decode(state) : 0,
      data: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/workletStart-request
const encoding2 = {
  preencode (state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.enableDebugLogs) c.uint.preencode(state, m.enableDebugLogs)
    if (m.seedPhrase) c.string.preencode(state, m.seedPhrase)
    if (m.seedBuffer) c.string.preencode(state, m.seedBuffer)
    c.string.preencode(state, m.config)
  },
  encode (state, m) {
    const flags =
      (m.enableDebugLogs ? 1 : 0) |
      (m.seedPhrase ? 2 : 0) |
      (m.seedBuffer ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.enableDebugLogs) c.uint.encode(state, m.enableDebugLogs)
    if (m.seedPhrase) c.string.encode(state, m.seedPhrase)
    if (m.seedBuffer) c.string.encode(state, m.seedBuffer)
    c.string.encode(state, m.config)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      enableDebugLogs: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      seedPhrase: (flags & 2) !== 0 ? c.string.decode(state) : null,
      seedBuffer: (flags & 4) !== 0 ? c.string.decode(state) : null,
      config: c.string.decode(state)
    }
  }
}

// @wdk-core/workletStart-response
const encoding3 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags = m.status ? 1 : 0

    c.uint.encode(state, flags)

    if (m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      status: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getAddress-request
const encoding4 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      network: r0,
      accountIndex: r1
    }
  }
}

// @wdk-core/getAddress-response
const encoding5 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.address) c.string.preencode(state, m.address)
  },
  encode (state, m) {
    const flags = m.address ? 1 : 0

    c.uint.encode(state, flags)

    if (m.address) c.string.encode(state, m.address)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      address: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getAddressBalance-request
const encoding6 = encoding4

// @wdk-core/getAddressBalance-response
const encoding7 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.balance) c.string.preencode(state, m.balance)
  },
  encode (state, m) {
    const flags = m.balance ? 1 : 0

    c.uint.encode(state, flags)

    if (m.balance) c.string.encode(state, m.balance)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      balance: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/quoteSendTransaction-request-options
const encoding8 = {
  preencode (state, m) {
    c.string.preencode(state, m.to)
    c.uint.preencode(state, m.value)
  },
  encode (state, m) {
    c.string.encode(state, m.to)
    c.uint.encode(state, m.value)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      to: r0,
      value: r1
    }
  }
}

// @wdk-core/quoteSendTransaction-request.options
const encoding9_2 = c.frame(encoding8)

// @wdk-core/quoteSendTransaction-request
const encoding9 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding9_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding9_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding9_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/quoteSendTransaction-response
const encoding10 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.fee) c.uint.preencode(state, m.fee)
  },
  encode (state, m) {
    const flags = m.fee ? 1 : 0

    c.uint.encode(state, flags)

    if (m.fee) c.uint.encode(state, m.fee)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      fee: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/sendTransaction-request-options
const encoding11 = encoding8

// @wdk-core/sendTransaction-request.options
const encoding12_2 = c.frame(encoding11)

// @wdk-core/sendTransaction-request
const encoding12 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding12_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding12_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding12_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/sendTransaction-response
const encoding13 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.fee) c.uint.preencode(state, m.fee)
    if (m.hash) c.string.preencode(state, m.hash)
  },
  encode (state, m) {
    const flags =
      (m.fee ? 1 : 0) |
      (m.hash ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.fee) c.uint.encode(state, m.fee)
    if (m.hash) c.string.encode(state, m.hash)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      fee: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      hash: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/getAbstractedAddress-request
const encoding14 = encoding4

// @wdk-core/getAbstractedAddress-response
const encoding15 = encoding5

// @wdk-core/getAbstractedAddressBalance-request
const encoding16 = encoding4

// @wdk-core/getAbstractedAddressBalance-response
const encoding17 = encoding7

// @wdk-core/getAbstractedAddressTokenBalance-request
const encoding18 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.tokenAddress)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.tokenAddress)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      tokenAddress: r2
    }
  }
}

// @wdk-core/getAbstractedAddressTokenBalance-response
const encoding19 = encoding7

// @wdk-core/abstractedAccountTransfer-request-options
const encoding20 = {
  preencode (state, m) {
    c.string.preencode(state, m.token)
    c.string.preencode(state, m.recipient)
    c.uint.preencode(state, m.amount)
  },
  encode (state, m) {
    c.string.encode(state, m.token)
    c.string.encode(state, m.recipient)
    c.uint.encode(state, m.amount)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)

    return {
      token: r0,
      recipient: r1,
      amount: r2
    }
  }
}

// @wdk-core/abstractedAccountTransfer-request.options
const encoding21_2 = c.frame(encoding20)

// @wdk-core/abstractedAccountTransfer-request
const encoding21 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding21_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding21_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding21_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/abstractedAccountTransfer-response
const encoding22 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.hash) c.string.preencode(state, m.hash)
    if (m.fee) c.uint.preencode(state, m.fee)
  },
  encode (state, m) {
    const flags =
      (m.hash ? 1 : 0) |
      (m.fee ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.hash) c.string.encode(state, m.hash)
    if (m.fee) c.uint.encode(state, m.fee)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      hash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fee: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/getApproveTransaction-request
const encoding23 = encoding20

// @wdk-core/getApproveTransaction-response
const encoding24 = {
  preencode (state, m) {
    c.string.preencode(state, m.to)
    c.uint.preencode(state, m.value)
    c.string.preencode(state, m.data)
  },
  encode (state, m) {
    c.string.encode(state, m.to)
    c.uint.encode(state, m.value)
    c.string.encode(state, m.data)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      to: r0,
      value: r1,
      data: r2
    }
  }
}

// @wdk-core/abstractedSendTransaction-request-options
const encoding25 = encoding24

// @wdk-core/abstractedSendTransaction-request-config
const encoding26 = {
  preencode (state, m) {
    c.string.preencode(state, m.paymasterToken)
  },
  encode (state, m) {
    c.string.encode(state, m.paymasterToken)
  },
  decode (state) {
    const r0 = c.string.decode(state)

    return {
      paymasterToken: r0
    }
  }
}

// @wdk-core/abstractedSendTransaction-request.config
const encoding27_3 = c.frame(encoding26)

// @wdk-core/abstractedSendTransaction-request
const encoding27 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.options)
    state.end++ // max flag is 1 so always one byte

    if (m.config) encoding27_3.preencode(state, m.config)
  },
  encode (state, m) {
    const flags = m.config ? 1 : 0

    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.options)
    c.uint.encode(state, flags)

    if (m.config) encoding27_3.encode(state, m.config)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2,
      config: (flags & 1) !== 0 ? encoding27_3.decode(state) : null
    }
  }
}

// @wdk-core/abstractedSendTransaction-response
const encoding28 = encoding22

// @wdk-core/abstractedAccountQuoteTransfer-request-options
const encoding29 = encoding20

// @wdk-core/abstractedAccountQuoteTransfer-request.options
const encoding30_2 = c.frame(encoding29)

// @wdk-core/abstractedAccountQuoteTransfer-request
const encoding30 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    encoding30_2.preencode(state, m.options)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    encoding30_2.encode(state, m.options)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = encoding30_2.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      options: r2
    }
  }
}

// @wdk-core/abstractedAccountQuoteTransfer-response
const encoding31 = encoding10

// @wdk-core/getTransactionReceipt-request
const encoding32 = {
  preencode (state, m) {
    c.string.preencode(state, m.network)
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.hash)
  },
  encode (state, m) {
    c.string.encode(state, m.network)
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.hash)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      network: r0,
      accountIndex: r1,
      hash: r2
    }
  }
}

// @wdk-core/getTransactionReceipt-response
const encoding33 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.receipt) c.string.preencode(state, m.receipt)
  },
  encode (state, m) {
    const flags = m.receipt ? 1 : 0

    c.uint.encode(state, flags)

    if (m.receipt) c.string.encode(state, m.receipt)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      receipt: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/dispose-request
const encoding34 = {
  preencode (state, m) {

  },
  encode (state, m) {

  },
  decode (state) {
    return {
    }
  }
}

// @wdk-core/rgbCreateUtxos-request
const encoding35 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    state.end++ // max flag is 8 so always one byte

    if (version >= 2 && m.upTo) c.uint.preencode(state, m.upTo)
    if (version >= 2 && m.num) c.uint.preencode(state, m.num)
    if (version >= 2 && m.size) c.uint.preencode(state, m.size)
    if (version >= 2 && m.feeRate) c.uint.preencode(state, m.feeRate)
  },
  encode (state, m) {
    const flags =
      ((version >= 2 && m.upTo) ? 1 : 0) |
      ((version >= 2 && m.num) ? 2 : 0) |
      ((version >= 2 && m.size) ? 4 : 0) |
      ((version >= 2 && m.feeRate) ? 8 : 0)

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, flags)

    if (version >= 2 && m.upTo) c.uint.encode(state, m.upTo)
    if (version >= 2 && m.num) c.uint.encode(state, m.num)
    if (version >= 2 && m.size) c.uint.encode(state, m.size)
    if (version >= 2 && m.feeRate) c.uint.encode(state, m.feeRate)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      upTo: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0,
      num: (version >= 2 && (flags & 2) !== 0) ? c.uint.decode(state) : 0,
      size: (version >= 2 && (flags & 4) !== 0) ? c.uint.decode(state) : 0,
      feeRate: (version >= 2 && (flags & 8) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbCreateUtxos-response
const encoding36 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.created) c.uint.preencode(state, m.created)
  },
  encode (state, m) {
    const flags = (version >= 2 && m.created) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 2 && m.created) c.uint.encode(state, m.created)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      created: (version >= 2 && (flags & 1) !== 0) ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbIssueAsset-request
const encoding37 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.ticker)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.amounts)
    c.uint.preencode(state, m.precision)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.ticker)
    c.string.encode(state, m.name)
    c.string.encode(state, m.amounts)
    c.uint.encode(state, m.precision)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)

    return {
      accountIndex: r0,
      ticker: r1,
      name: r2,
      amounts: r3,
      precision: r4
    }
  }
}

// @wdk-core/rgbIssueAsset-response
const encoding38 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.assetId) c.string.preencode(state, m.assetId)
    if (version >= 2 && m.details) c.string.preencode(state, m.details)
  },
  encode (state, m) {
    const flags =
      ((version >= 2 && m.assetId) ? 1 : 0) |
      ((version >= 2 && m.details) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.assetId) c.string.encode(state, m.assetId)
    if (version >= 2 && m.details) c.string.encode(state, m.details)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      assetId: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null,
      details: (version >= 2 && (flags & 2) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListAssets-request
const encoding39 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
  },
  decode (state) {
    const r0 = c.uint.decode(state)

    return {
      accountIndex: r0
    }
  }
}

// @wdk-core/rgbListAssets-response
const encoding40 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.assets) c.string.preencode(state, m.assets)
  },
  encode (state, m) {
    const flags = (version >= 2 && m.assets) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 2 && m.assets) c.string.encode(state, m.assets)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      assets: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbRefresh-request
const encoding41 = encoding39

// @wdk-core/rgbRefresh-response
const encoding42 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags = (version >= 2 && m.status) ? 1 : 0

    c.uint.encode(state, flags)

    if (version >= 2 && m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      status: (version >= 2 && (flags & 1) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbBlindReceive-request
const encoding43 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    state.end++ // max flag is 4 so always one byte

    if (m.assetId) c.string.preencode(state, m.assetId)
    if (m.amount) c.uint.preencode(state, m.amount)
    if (m.transportEndpoints) c.string.preencode(state, m.transportEndpoints)
  },
  encode (state, m) {
    const flags =
      (m.assetId ? 1 : 0) |
      (m.amount ? 2 : 0) |
      (m.transportEndpoints ? 4 : 0)

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, flags)

    if (m.assetId) c.string.encode(state, m.assetId)
    if (m.amount) c.uint.encode(state, m.amount)
    if (m.transportEndpoints) c.string.encode(state, m.transportEndpoints)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      assetId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      amount: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      transportEndpoints: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbBlindReceive-response
const encoding44 = {
  preencode (state, m) {
    state.end++ // max flag is 4 so always one byte

    if (m.invoice) c.string.preencode(state, m.invoice)
    if (m.recipientId) c.string.preencode(state, m.recipientId)
    if (m.expirationTimestamp) c.uint.preencode(state, m.expirationTimestamp)
  },
  encode (state, m) {
    const flags =
      (m.invoice ? 1 : 0) |
      (m.recipientId ? 2 : 0) |
      (m.expirationTimestamp ? 4 : 0)

    c.uint.encode(state, flags)

    if (m.invoice) c.string.encode(state, m.invoice)
    if (m.recipientId) c.string.encode(state, m.recipientId)
    if (m.expirationTimestamp) c.uint.encode(state, m.expirationTimestamp)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      invoice: (flags & 1) !== 0 ? c.string.decode(state) : null,
      recipientId: (flags & 2) !== 0 ? c.string.decode(state) : null,
      expirationTimestamp: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbWitnessReceive-request
const encoding45 = encoding43

// @wdk-core/rgbWitnessReceive-response
const encoding46 = encoding44

// @wdk-core/rgbSend-request
const encoding47 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.token)
    c.string.preencode(state, m.recipient)
    c.uint.preencode(state, m.amount)
    state.end++ // max flag is 2 so always one byte

    if (m.feeRate) c.uint.preencode(state, m.feeRate)
    if (m.minConfirmations) c.uint.preencode(state, m.minConfirmations)
  },
  encode (state, m) {
    const flags =
      (m.feeRate ? 1 : 0) |
      (m.minConfirmations ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.token)
    c.string.encode(state, m.recipient)
    c.uint.encode(state, m.amount)
    c.uint.encode(state, flags)

    if (m.feeRate) c.uint.encode(state, m.feeRate)
    if (m.minConfirmations) c.uint.encode(state, m.minConfirmations)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      token: r1,
      recipient: r2,
      amount: r3,
      feeRate: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      minConfirmations: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbSend-response
const encoding48 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.hash) c.string.preencode(state, m.hash)
    if (m.fee) c.string.preencode(state, m.fee)
  },
  encode (state, m) {
    const flags =
      (m.hash ? 1 : 0) |
      (m.fee ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.hash) c.string.encode(state, m.hash)
    if (m.fee) c.string.encode(state, m.fee)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      hash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fee: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbGetAssetBalance-request
const encoding49 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.assetId)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.assetId)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)

    return {
      accountIndex: r0,
      assetId: r1
    }
  }
}

// @wdk-core/rgbGetAssetBalance-response
const encoding50 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.balance) c.string.preencode(state, m.balance)
  },
  encode (state, m) {
    const flags = m.balance ? 1 : 0

    c.uint.encode(state, flags)

    if (m.balance) c.string.encode(state, m.balance)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      balance: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListTransfers-request
const encoding51 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    state.end++ // max flag is 1 so always one byte

    if (m.assetId) c.string.preencode(state, m.assetId)
  },
  encode (state, m) {
    const flags = m.assetId ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, flags)

    if (m.assetId) c.string.encode(state, m.assetId)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      assetId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListTransfers-response
const encoding52 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.transfers) c.string.preencode(state, m.transfers)
  },
  encode (state, m) {
    const flags = m.transfers ? 1 : 0

    c.uint.encode(state, flags)

    if (m.transfers) c.string.encode(state, m.transfers)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      transfers: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListTransactions-request
const encoding53 = encoding39

// @wdk-core/rgbListTransactions-response
const encoding54 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.transactions) c.string.preencode(state, m.transactions)
  },
  encode (state, m) {
    const flags = m.transactions ? 1 : 0

    c.uint.encode(state, flags)

    if (m.transactions) c.string.encode(state, m.transactions)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      transactions: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbSendBtc-request
const encoding55 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.to)
    c.string.preencode(state, m.value)
    state.end++ // max flag is 1 so always one byte

    if (m.feeRate) c.uint.preencode(state, m.feeRate)
  },
  encode (state, m) {
    const flags = m.feeRate ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.to)
    c.string.encode(state, m.value)
    c.uint.encode(state, flags)

    if (m.feeRate) c.uint.encode(state, m.feeRate)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      to: r1,
      value: r2,
      feeRate: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbSendBtc-response
const encoding56 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.hash) c.string.preencode(state, m.hash)
    if (m.fee) c.string.preencode(state, m.fee)
  },
  encode (state, m) {
    const flags =
      (m.hash ? 1 : 0) |
      (m.fee ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.hash) c.string.encode(state, m.hash)
    if (m.fee) c.string.encode(state, m.fee)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      hash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      fee: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbIssueAssetCfa-request
const encoding57 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.precision)
    c.string.preencode(state, m.amounts)
    state.end++ // max flag is 2 so always one byte

    if (m.details) c.string.preencode(state, m.details)
    if (m.filePath) c.string.preencode(state, m.filePath)
  },
  encode (state, m) {
    const flags =
      (m.details ? 1 : 0) |
      (m.filePath ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.precision)
    c.string.encode(state, m.amounts)
    c.uint.encode(state, flags)

    if (m.details) c.string.encode(state, m.details)
    if (m.filePath) c.string.encode(state, m.filePath)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      name: r1,
      precision: r2,
      amounts: r3,
      details: (flags & 1) !== 0 ? c.string.decode(state) : null,
      filePath: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbIssueAssetCfa-response
const encoding58 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.assetId) c.string.preencode(state, m.assetId)
    if (m.details) c.string.preencode(state, m.details)
  },
  encode (state, m) {
    const flags =
      (m.assetId ? 1 : 0) |
      (m.details ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.assetId) c.string.encode(state, m.assetId)
    if (m.details) c.string.encode(state, m.details)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      assetId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      details: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbIssueAssetUda-request
const encoding59 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.ticker)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.precision)
    state.end++ // max flag is 4 so always one byte

    if (m.details) c.string.preencode(state, m.details)
    if (m.mediaFilePath) c.string.preencode(state, m.mediaFilePath)
    if (m.attachmentsFilePaths) c.string.preencode(state, m.attachmentsFilePaths)
  },
  encode (state, m) {
    const flags =
      (m.details ? 1 : 0) |
      (m.mediaFilePath ? 2 : 0) |
      (m.attachmentsFilePaths ? 4 : 0)

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.ticker)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.precision)
    c.uint.encode(state, flags)

    if (m.details) c.string.encode(state, m.details)
    if (m.mediaFilePath) c.string.encode(state, m.mediaFilePath)
    if (m.attachmentsFilePaths) c.string.encode(state, m.attachmentsFilePaths)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      ticker: r1,
      name: r2,
      precision: r3,
      details: (flags & 1) !== 0 ? c.string.decode(state) : null,
      mediaFilePath: (flags & 2) !== 0 ? c.string.decode(state) : null,
      attachmentsFilePaths: (flags & 4) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbIssueAssetUda-response
const encoding60 = encoding58

// @wdk-core/rgbInflate-request
const encoding61 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.assetId)
    c.string.preencode(state, m.amounts)
    state.end++ // max flag is 2 so always one byte

    if (m.feeRate) c.uint.preencode(state, m.feeRate)
    if (m.minConfirmations) c.uint.preencode(state, m.minConfirmations)
  },
  encode (state, m) {
    const flags =
      (m.feeRate ? 1 : 0) |
      (m.minConfirmations ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.assetId)
    c.string.encode(state, m.amounts)
    c.uint.encode(state, flags)

    if (m.feeRate) c.uint.encode(state, m.feeRate)
    if (m.minConfirmations) c.uint.encode(state, m.minConfirmations)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      assetId: r1,
      amounts: r2,
      feeRate: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      minConfirmations: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbInflate-response
const encoding62 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.details) c.string.preencode(state, m.details)
  },
  encode (state, m) {
    const flags = m.details ? 1 : 0

    c.uint.encode(state, flags)

    if (m.details) c.string.encode(state, m.details)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      details: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListUnspents-request
const encoding63 = encoding39

// @wdk-core/rgbListUnspents-response
const encoding64 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.unspents) c.string.preencode(state, m.unspents)
  },
  encode (state, m) {
    const flags = m.unspents ? 1 : 0

    c.uint.encode(state, flags)

    if (m.unspents) c.string.encode(state, m.unspents)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      unspents: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbEstimateFee-request
const encoding65 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    state.end++ // max flag is 1 so always one byte

    if (m.blocks) c.uint.preencode(state, m.blocks)
  },
  encode (state, m) {
    const flags = m.blocks ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, flags)

    if (m.blocks) c.uint.encode(state, m.blocks)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      blocks: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbEstimateFee-response
const encoding66 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.feeRate) c.string.preencode(state, m.feeRate)
  },
  encode (state, m) {
    const flags = m.feeRate ? 1 : 0

    c.uint.encode(state, flags)

    if (m.feeRate) c.string.encode(state, m.feeRate)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      feeRate: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbSync-request
const encoding67 = encoding39

// @wdk-core/rgbSync-response
const encoding68 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags = m.status ? 1 : 0

    c.uint.encode(state, flags)

    if (m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      status: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbCreateBackup-request
const encoding69 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.password)
    c.string.preencode(state, m.backupPath)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.password)
    c.string.encode(state, m.backupPath)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)

    return {
      accountIndex: r0,
      password: r1,
      backupPath: r2
    }
  }
}

// @wdk-core/rgbCreateBackup-response
const encoding70 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.message) c.string.preencode(state, m.message)
    if (m.downloadUrl) c.string.preencode(state, m.downloadUrl)
  },
  encode (state, m) {
    const flags =
      (m.message ? 1 : 0) |
      (m.downloadUrl ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
    if (m.downloadUrl) c.string.encode(state, m.downloadUrl)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      message: (flags & 1) !== 0 ? c.string.decode(state) : null,
      downloadUrl: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbRestoreFromBackup-request
const encoding71 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.password)
    c.string.preencode(state, m.backupFilePath)
    c.string.preencode(state, m.dataDir)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.password)
    c.string.encode(state, m.backupFilePath)
    c.string.encode(state, m.dataDir)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)

    return {
      accountIndex: r0,
      password: r1,
      backupFilePath: r2,
      dataDir: r3
    }
  }
}

// @wdk-core/rgbRestoreFromBackup-response
const encoding72 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.message) c.string.preencode(state, m.message)
  },
  encode (state, m) {
    const flags = m.message ? 1 : 0

    c.uint.encode(state, flags)

    if (m.message) c.string.encode(state, m.message)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      message: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbBackupInfo-request
const encoding73 = encoding39

// @wdk-core/rgbBackupInfo-response
const encoding74 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.string.preencode(state, m.info)
  },
  encode (state, m) {
    const flags = m.info ? 1 : 0

    c.uint.encode(state, flags)

    if (m.info) c.string.encode(state, m.info)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      info: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbSignMessage-request
const encoding75 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.message)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.message)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)

    return {
      accountIndex: r0,
      message: r1
    }
  }
}

// @wdk-core/rgbSignMessage-response
const encoding76 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.signature) c.string.preencode(state, m.signature)
  },
  encode (state, m) {
    const flags = m.signature ? 1 : 0

    c.uint.encode(state, flags)

    if (m.signature) c.string.encode(state, m.signature)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      signature: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbVerifyMessage-request
const encoding77 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.message)
    c.string.preencode(state, m.signature)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.message)
    c.string.encode(state, m.signature)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)

    return {
      accountIndex: r0,
      message: r1,
      signature: r2
    }
  }
}

// @wdk-core/rgbVerifyMessage-response
const encoding78 = {
  preencode (state, m) {
    c.bool.preencode(state, m.valid)
  },
  encode (state, m) {
    c.bool.encode(state, m.valid)
  },
  decode (state) {
    return {
      valid: c.bool.decode(state)
    }
  }
}

// @wdk-core/rgbSendBegin-request
const encoding79 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.invoice)
    c.string.preencode(state, m.assetId)
    c.uint.preencode(state, m.amount)
    state.end++ // max flag is 2 so always one byte

    if (m.feeRate) c.uint.preencode(state, m.feeRate)
    if (m.minConfirmations) c.uint.preencode(state, m.minConfirmations)
  },
  encode (state, m) {
    const flags =
      (m.feeRate ? 1 : 0) |
      (m.minConfirmations ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.invoice)
    c.string.encode(state, m.assetId)
    c.uint.encode(state, m.amount)
    c.uint.encode(state, flags)

    if (m.feeRate) c.uint.encode(state, m.feeRate)
    if (m.minConfirmations) c.uint.encode(state, m.minConfirmations)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      invoice: r1,
      assetId: r2,
      amount: r3,
      feeRate: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      minConfirmations: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbSendBegin-response
const encoding80 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.psbt) c.string.preencode(state, m.psbt)
  },
  encode (state, m) {
    const flags = m.psbt ? 1 : 0

    c.uint.encode(state, flags)

    if (m.psbt) c.string.encode(state, m.psbt)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      psbt: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbSendEnd-request
const encoding81 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.signedPsbt)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.signedPsbt)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)

    return {
      accountIndex: r0,
      signedPsbt: r1
    }
  }
}

// @wdk-core/rgbSendEnd-response
const encoding82 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.txid) c.string.preencode(state, m.txid)
    if (m.details) c.string.preencode(state, m.details)
  },
  encode (state, m) {
    const flags =
      (m.txid ? 1 : 0) |
      (m.details ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.txid) c.string.encode(state, m.txid)
    if (m.details) c.string.encode(state, m.details)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      txid: (flags & 1) !== 0 ? c.string.decode(state) : null,
      details: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbCreateLightningInvoice-request
const encoding83 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.uint.preencode(state, m.amount)
    state.end++ // max flag is 2 so always one byte

    if (m.description) c.string.preencode(state, m.description)
    if (m.expiry) c.uint.preencode(state, m.expiry)
  },
  encode (state, m) {
    const flags =
      (m.description ? 1 : 0) |
      (m.expiry ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, m.amount)
    c.uint.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.expiry) c.uint.encode(state, m.expiry)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      amount: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      expiry: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbCreateLightningInvoice-response
const encoding84 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.invoice) c.string.preencode(state, m.invoice)
    if (m.paymentHash) c.string.preencode(state, m.paymentHash)
  },
  encode (state, m) {
    const flags =
      (m.invoice ? 1 : 0) |
      (m.paymentHash ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.invoice) c.string.encode(state, m.invoice)
    if (m.paymentHash) c.string.encode(state, m.paymentHash)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      invoice: (flags & 1) !== 0 ? c.string.decode(state) : null,
      paymentHash: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbPayLightningInvoice-request
const encoding85 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.invoice)
    state.end++ // max flag is 1 so always one byte

    if (m.amount) c.uint.preencode(state, m.amount)
  },
  encode (state, m) {
    const flags = m.amount ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.invoice)
    c.uint.encode(state, flags)

    if (m.amount) c.uint.encode(state, m.amount)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      invoice: r1,
      amount: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbPayLightningInvoice-response
const encoding86 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.paymentHash) c.string.preencode(state, m.paymentHash)
    if (m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags =
      (m.paymentHash ? 1 : 0) |
      (m.status ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.paymentHash) c.string.encode(state, m.paymentHash)
    if (m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      paymentHash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      status: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbOnchainReceive-request
const encoding87 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    state.end++ // max flag is 2 so always one byte

    if (m.amount) c.uint.preencode(state, m.amount)
    if (m.assetId) c.string.preencode(state, m.assetId)
  },
  encode (state, m) {
    const flags =
      (m.amount ? 1 : 0) |
      (m.assetId ? 2 : 0)

    c.uint.encode(state, m.accountIndex)
    c.uint.encode(state, flags)

    if (m.amount) c.uint.encode(state, m.amount)
    if (m.assetId) c.string.encode(state, m.assetId)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      amount: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      assetId: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbOnchainReceive-response
const encoding88 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.address) c.string.preencode(state, m.address)
    if (m.invoice) c.string.preencode(state, m.invoice)
  },
  encode (state, m) {
    const flags =
      (m.address ? 1 : 0) |
      (m.invoice ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.address) c.string.encode(state, m.address)
    if (m.invoice) c.string.encode(state, m.invoice)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      address: (flags & 1) !== 0 ? c.string.decode(state) : null,
      invoice: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbOnchainSend-request
const encoding89 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.to)
    c.uint.preencode(state, m.amount)
    state.end++ // max flag is 1 so always one byte

    if (m.assetId) c.string.preencode(state, m.assetId)
  },
  encode (state, m) {
    const flags = m.assetId ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.to)
    c.uint.encode(state, m.amount)
    c.uint.encode(state, flags)

    if (m.assetId) c.string.encode(state, m.assetId)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      to: r1,
      amount: r2,
      assetId: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbOnchainSend-response
const encoding90 = {
  preencode (state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.hash) c.string.preencode(state, m.hash)
    if (m.status) c.string.preencode(state, m.status)
  },
  encode (state, m) {
    const flags =
      (m.hash ? 1 : 0) |
      (m.status ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.hash) c.string.encode(state, m.hash)
    if (m.status) c.string.encode(state, m.status)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      hash: (flags & 1) !== 0 ? c.string.decode(state) : null,
      status: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbListLightningPayments-request
const encoding91 = encoding39

// @wdk-core/rgbListLightningPayments-response
const encoding92 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.payments) c.string.preencode(state, m.payments)
  },
  encode (state, m) {
    const flags = m.payments ? 1 : 0

    c.uint.encode(state, flags)

    if (m.payments) c.string.encode(state, m.payments)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      payments: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbCreateUtxosBegin-request
const encoding93 = encoding35

// @wdk-core/rgbCreateUtxosBegin-response
const encoding94 = encoding80

// @wdk-core/rgbCreateUtxosEnd-request
const encoding95 = encoding81

// @wdk-core/rgbCreateUtxosEnd-response
const encoding96 = encoding36

// @wdk-core/rgbSendBtcBegin-request
const encoding97 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.address)
    c.string.preencode(state, m.amount)
    state.end++ // max flag is 1 so always one byte

    if (m.feeRate) c.uint.preencode(state, m.feeRate)
  },
  encode (state, m) {
    const flags = m.feeRate ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.address)
    c.string.encode(state, m.amount)
    c.uint.encode(state, flags)

    if (m.feeRate) c.uint.encode(state, m.feeRate)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      address: r1,
      amount: r2,
      feeRate: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @wdk-core/rgbSendBtcBegin-response
const encoding98 = encoding80

// @wdk-core/rgbSendBtcEnd-request
const encoding99 = encoding81

// @wdk-core/rgbSendBtcEnd-response
const encoding100 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.txid) c.string.preencode(state, m.txid)
  },
  encode (state, m) {
    const flags = m.txid ? 1 : 0

    c.uint.encode(state, flags)

    if (m.txid) c.string.encode(state, m.txid)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      txid: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbDecodeInvoice-request
const encoding101 = {
  preencode (state, m) {
    c.string.preencode(state, m.invoice)
  },
  encode (state, m) {
    c.string.encode(state, m.invoice)
  },
  decode (state) {
    return {
      invoice: c.string.decode(state)
    }
  }
}

// @wdk-core/rgbDecodeInvoice-response
const encoding102 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.data) c.string.preencode(state, m.data)
  },
  encode (state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, flags)

    if (m.data) c.string.encode(state, m.data)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      data: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbFinalizePsbt-request
const encoding103 = encoding81

// @wdk-core/rgbFinalizePsbt-response
const encoding104 = encoding80

// @wdk-core/rgbSignPsbt-request
const encoding105 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.unsignedPsbt)
  },
  encode (state, m) {
    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.unsignedPsbt)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)

    return {
      accountIndex: r0,
      unsignedPsbt: r1
    }
  }
}

// @wdk-core/rgbSignPsbt-response
const encoding106 = encoding80

// @wdk-core/rgbInvoiceNew-request
const encoding107 = encoding101

// @wdk-core/rgbInvoiceNew-response
const encoding108 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.invoice) c.string.preencode(state, m.invoice)
  },
  encode (state, m) {
    const flags = m.invoice ? 1 : 0

    c.uint.encode(state, flags)

    if (m.invoice) c.string.encode(state, m.invoice)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      invoice: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbInvoiceData-request
const encoding109 = encoding101

// @wdk-core/rgbInvoiceData-response
const encoding110 = encoding102

// @wdk-core/rgbInvoiceString-request
const encoding111 = encoding101

// @wdk-core/rgbInvoiceString-response
const encoding112 = encoding108

// @wdk-core/rgbIssueAssetIfa-request
const encoding113 = {
  preencode (state, m) {
    c.uint.preencode(state, m.accountIndex)
    c.string.preencode(state, m.ticker)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.precision)
    c.string.preencode(state, m.amounts)
    c.string.preencode(state, m.inflationAmounts)
    state.end++ // max flag is 1 so always one byte

    if (m.rejectListUrl) c.string.preencode(state, m.rejectListUrl)
  },
  encode (state, m) {
    const flags = m.rejectListUrl ? 1 : 0

    c.uint.encode(state, m.accountIndex)
    c.string.encode(state, m.ticker)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.precision)
    c.string.encode(state, m.amounts)
    c.string.encode(state, m.inflationAmounts)
    c.uint.encode(state, flags)

    if (m.rejectListUrl) c.string.encode(state, m.rejectListUrl)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      accountIndex: r0,
      ticker: r1,
      name: r2,
      precision: r3,
      amounts: r4,
      inflationAmounts: r5,
      rejectListUrl: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-core/rgbIssueAssetIfa-response
const encoding114 = encoding58

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    case '@wdk-core/log-type-enum': return encoding0_enum
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@wdk-core/log-type-enum': return encoding0
    case '@wdk-core/log-request': return encoding1
    case '@wdk-core/workletStart-request': return encoding2
    case '@wdk-core/workletStart-response': return encoding3
    case '@wdk-core/getAddress-request': return encoding4
    case '@wdk-core/getAddress-response': return encoding5
    case '@wdk-core/getAddressBalance-request': return encoding6
    case '@wdk-core/getAddressBalance-response': return encoding7
    case '@wdk-core/quoteSendTransaction-request-options': return encoding8
    case '@wdk-core/quoteSendTransaction-request': return encoding9
    case '@wdk-core/quoteSendTransaction-response': return encoding10
    case '@wdk-core/sendTransaction-request-options': return encoding11
    case '@wdk-core/sendTransaction-request': return encoding12
    case '@wdk-core/sendTransaction-response': return encoding13
    case '@wdk-core/getAbstractedAddress-request': return encoding14
    case '@wdk-core/getAbstractedAddress-response': return encoding15
    case '@wdk-core/getAbstractedAddressBalance-request': return encoding16
    case '@wdk-core/getAbstractedAddressBalance-response': return encoding17
    case '@wdk-core/getAbstractedAddressTokenBalance-request': return encoding18
    case '@wdk-core/getAbstractedAddressTokenBalance-response': return encoding19
    case '@wdk-core/abstractedAccountTransfer-request-options': return encoding20
    case '@wdk-core/abstractedAccountTransfer-request': return encoding21
    case '@wdk-core/abstractedAccountTransfer-response': return encoding22
    case '@wdk-core/getApproveTransaction-request': return encoding23
    case '@wdk-core/getApproveTransaction-response': return encoding24
    case '@wdk-core/abstractedSendTransaction-request-options': return encoding25
    case '@wdk-core/abstractedSendTransaction-request-config': return encoding26
    case '@wdk-core/abstractedSendTransaction-request': return encoding27
    case '@wdk-core/abstractedSendTransaction-response': return encoding28
    case '@wdk-core/abstractedAccountQuoteTransfer-request-options': return encoding29
    case '@wdk-core/abstractedAccountQuoteTransfer-request': return encoding30
    case '@wdk-core/abstractedAccountQuoteTransfer-response': return encoding31
    case '@wdk-core/getTransactionReceipt-request': return encoding32
    case '@wdk-core/getTransactionReceipt-response': return encoding33
    case '@wdk-core/dispose-request': return encoding34
    case '@wdk-core/rgbCreateUtxos-request': return encoding35
    case '@wdk-core/rgbCreateUtxos-response': return encoding36
    case '@wdk-core/rgbIssueAsset-request': return encoding37
    case '@wdk-core/rgbIssueAsset-response': return encoding38
    case '@wdk-core/rgbListAssets-request': return encoding39
    case '@wdk-core/rgbListAssets-response': return encoding40
    case '@wdk-core/rgbRefresh-request': return encoding41
    case '@wdk-core/rgbRefresh-response': return encoding42
    case '@wdk-core/rgbBlindReceive-request': return encoding43
    case '@wdk-core/rgbBlindReceive-response': return encoding44
    case '@wdk-core/rgbWitnessReceive-request': return encoding45
    case '@wdk-core/rgbWitnessReceive-response': return encoding46
    case '@wdk-core/rgbSend-request': return encoding47
    case '@wdk-core/rgbSend-response': return encoding48
    case '@wdk-core/rgbGetAssetBalance-request': return encoding49
    case '@wdk-core/rgbGetAssetBalance-response': return encoding50
    case '@wdk-core/rgbListTransfers-request': return encoding51
    case '@wdk-core/rgbListTransfers-response': return encoding52
    case '@wdk-core/rgbListTransactions-request': return encoding53
    case '@wdk-core/rgbListTransactions-response': return encoding54
    case '@wdk-core/rgbSendBtc-request': return encoding55
    case '@wdk-core/rgbSendBtc-response': return encoding56
    case '@wdk-core/rgbIssueAssetCfa-request': return encoding57
    case '@wdk-core/rgbIssueAssetCfa-response': return encoding58
    case '@wdk-core/rgbIssueAssetUda-request': return encoding59
    case '@wdk-core/rgbIssueAssetUda-response': return encoding60
    case '@wdk-core/rgbInflate-request': return encoding61
    case '@wdk-core/rgbInflate-response': return encoding62
    case '@wdk-core/rgbListUnspents-request': return encoding63
    case '@wdk-core/rgbListUnspents-response': return encoding64
    case '@wdk-core/rgbEstimateFee-request': return encoding65
    case '@wdk-core/rgbEstimateFee-response': return encoding66
    case '@wdk-core/rgbSync-request': return encoding67
    case '@wdk-core/rgbSync-response': return encoding68
    case '@wdk-core/rgbCreateBackup-request': return encoding69
    case '@wdk-core/rgbCreateBackup-response': return encoding70
    case '@wdk-core/rgbRestoreFromBackup-request': return encoding71
    case '@wdk-core/rgbRestoreFromBackup-response': return encoding72
    case '@wdk-core/rgbBackupInfo-request': return encoding73
    case '@wdk-core/rgbBackupInfo-response': return encoding74
    case '@wdk-core/rgbSignMessage-request': return encoding75
    case '@wdk-core/rgbSignMessage-response': return encoding76
    case '@wdk-core/rgbVerifyMessage-request': return encoding77
    case '@wdk-core/rgbVerifyMessage-response': return encoding78
    case '@wdk-core/rgbSendBegin-request': return encoding79
    case '@wdk-core/rgbSendBegin-response': return encoding80
    case '@wdk-core/rgbSendEnd-request': return encoding81
    case '@wdk-core/rgbSendEnd-response': return encoding82
    case '@wdk-core/rgbCreateLightningInvoice-request': return encoding83
    case '@wdk-core/rgbCreateLightningInvoice-response': return encoding84
    case '@wdk-core/rgbPayLightningInvoice-request': return encoding85
    case '@wdk-core/rgbPayLightningInvoice-response': return encoding86
    case '@wdk-core/rgbOnchainReceive-request': return encoding87
    case '@wdk-core/rgbOnchainReceive-response': return encoding88
    case '@wdk-core/rgbOnchainSend-request': return encoding89
    case '@wdk-core/rgbOnchainSend-response': return encoding90
    case '@wdk-core/rgbListLightningPayments-request': return encoding91
    case '@wdk-core/rgbListLightningPayments-response': return encoding92
    case '@wdk-core/rgbCreateUtxosBegin-request': return encoding93
    case '@wdk-core/rgbCreateUtxosBegin-response': return encoding94
    case '@wdk-core/rgbCreateUtxosEnd-request': return encoding95
    case '@wdk-core/rgbCreateUtxosEnd-response': return encoding96
    case '@wdk-core/rgbSendBtcBegin-request': return encoding97
    case '@wdk-core/rgbSendBtcBegin-response': return encoding98
    case '@wdk-core/rgbSendBtcEnd-request': return encoding99
    case '@wdk-core/rgbSendBtcEnd-response': return encoding100
    case '@wdk-core/rgbDecodeInvoice-request': return encoding101
    case '@wdk-core/rgbDecodeInvoice-response': return encoding102
    case '@wdk-core/rgbFinalizePsbt-request': return encoding103
    case '@wdk-core/rgbFinalizePsbt-response': return encoding104
    case '@wdk-core/rgbSignPsbt-request': return encoding105
    case '@wdk-core/rgbSignPsbt-response': return encoding106
    case '@wdk-core/rgbInvoiceNew-request': return encoding107
    case '@wdk-core/rgbInvoiceNew-response': return encoding108
    case '@wdk-core/rgbInvoiceData-request': return encoding109
    case '@wdk-core/rgbInvoiceData-response': return encoding110
    case '@wdk-core/rgbInvoiceString-request': return encoding111
    case '@wdk-core/rgbInvoiceString-response': return encoding112
    case '@wdk-core/rgbIssueAssetIfa-request': return encoding113
    case '@wdk-core/rgbIssueAssetIfa-response': return encoding114
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
