/**
 * Enumeration for all available error codes
 *
 * @enum {string}
 */
const ERROR_CODES = {
  UNKNOWN: 'UNKNOWN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ACCOUNT_BALANCES: 'ACCOUNT_BALANCES',
  WDK_MANAGER_INIT: 'WDK_MANAGER_INIT',
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST'
}

module.exports = ERROR_CODES
