// Internal dependencies - utilities
const logger = require('./utils/logger')

// Generated dependencies
const HRPC = require('../generated/hrpc')

// RPC handlers
const { registerRpcHandlers } = require('./rpc-handlers')

// Handle unhandled promise rejections and exceptions
if (typeof process !== 'undefined' && process.on) {
  process.on('unhandledRejection', (error) => {
    logger.error('Unhandled promise rejection in worklet:', error)
  })
  process.on('uncaughtException', (error) => {
    logger.error('Uncaught exception in worklet:', error)
  })
}

// Initialize core dependencies
// eslint-disable-next-line no-undef
const { IPC: BareIPC } = BareKit

// Load wallet modules from generated file (ensures proper bundling)
// This file is generated by scripts/generate-wallet-modules.js from schema.json
let WDK = null
let walletManagers = {}
let requiredNetworks = []
let wdkLoadError = null

try {
  const walletModules = require('../generated/wallet-modules.js')
  WDK = walletModules.WDK
  walletManagers = walletModules.walletManagers
  requiredNetworks = walletModules.requiredNetworks
  
  logger.info('Loaded wallet modules:', Object.keys(walletManagers).join(', '))
} catch (error) {
  wdkLoadError = {
    message: error?.message || String(error),
    stack: error?.stack,
    name: error?.name,
    code: error?.code
  }
  WDK = null
  walletManagers = {}
  requiredNetworks = []
}

// Initialize RPC
const rpc = new HRPC(BareIPC)

// State - this will be managed by the RPC handlers
let wdk = null

// Create context object for RPC handlers
// This allows handlers to read and update the wdk state
const context = {
  get wdk() {
    return wdk
  },
  set wdk(value) {
    wdk = value
  },
  WDK,
  walletManagers,
  requiredNetworks,
  wdkLoadError
}

// Register all RPC handlers
registerRpcHandlers(rpc, context)
